sudo: false
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux

env:
  global:
  - PYTHONUNBUFFERED=yes
  - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@localhost:5432/erpro_test
  - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/erpro_test
  - CLOUDAMQP_URL=amqp://guest:guest@127.0.0.1:5672/
  - SECRET_KEY=travis_ci

#virtualenv:
#  system_site_packages: true

branches:
  only:
  - master

#before_install:
#  - pip install -r requirements-test.txt
  
install:
  - pip install -r requirements.txt

before_script:
  - psql -c "create database erpro_test;" -U postgres
  - psql -c "alter user postgres with password 'postgres';"
  - export FLASK_APP="$TRAVIS_BUILD_DIR/erpro/service/core.py"
  - flask db upgrade

script:
  - pytest --cov=codecov

services:
  - postgresql
  - rabbitmq

after_success:
  - codecov
