version: '3'

services:

  postgres_database:
    image: postgres:10-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
    - "5432:5432"

  rabbitmq_message_broker:
    image: rabbitmq:3-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
    - "5672:5672"

  nginx_reverse_proxy:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
#    networks:
#      - ngnix-network

  flask_server:
    image: foobar_api_server:latest
    build:
      context: .
      dockerfile: Dockerfile-apiapp
    container_name: flask
    restart: unless-stopped
    expose:
      - 8000
    depends_on:
    - postgres_database
    - nginx_reverse_proxy
    - rabbitmq_message_broker
#    networks:
#      - ngnix-network
    volumes:
    - logs:/foobar/logs
    env_file:
    - .env

  celery_worker:
    image: foobar_worker:latest
    build:
      context: .
      dockerfile: Dockerfile-worker
    container_name: celery
    restart: unless-stopped
    depends_on:
    - postgres_database
    - rabbitmq_message_broker
    volumes:
    - logs:/foobar/logs
    env_file:
    - .env


volumes:
  logs:

#networks:
#  ngnix-network:
#    driver: bridge